In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 

In [ ]:
dataset1 = pd.read_csv('gender_submission.csv')
dataset2 = pd.read_csv('test.csv')
dataset3 = pd.read_csv('train.csv')
train_x = dataset3.iloc[ : , 2 : 11 ].values
test_x = dataset2.iloc[ : , 1 : 9 ].values
test_x = pd.DataFrame(test_x)
train_x = pd.DataFrame(train_x)
train_x = train_x.drop(labels = None , axis = 0 , columns = 1 )
train_x = train_x.drop(labels = None , axis = 0 , columns = 8 )
train_x = train_x.drop(labels = None , axis = 0 , columns = 6 )
train_x = train_x.iloc[ : , : ].values 
test_x = test_x.drop(labels = None , axis = 0 , columns = 1)
test_x = test_x.drop(labels = None , axis = 0 , columns = 6)
test_x = test_x.iloc[ : , : ].values 
print(test_x.shape) 
print(train_x.shape)
print(train_x)
print(test_x)



(418, 6)
(891, 6)
[[3 'male' 22.0 1 0 7.25]
 [1 'female' 38.0 1 0 71.2833]
 [3 'female' 26.0 0 0 7.925]
 ...
 [3 'female' nan 1 2 23.45]
 [1 'male' 26.0 0 0 30.0]
 [3 'male' 32.0 0 0 7.75]]
[[3 'male' 34.5 0 0 7.8292]
 [3 'female' 47.0 1 0 7.0]
 [2 'male' 62.0 0 0 9.6875]
 ...
 [3 'male' 38.5 0 0 7.25]
 [3 'male' nan 0 0 8.05]
 [3 'male' nan 1 1 22.3583]]


In [ ]:
train_y = dataset3.iloc[ : , 1].values
print(train_y)
test_y = dataset1.iloc[ : , 1].values
print(test_y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
le = LabelEncoder()
train_x[ : , 1] = le.fit_transform(train_x[ : , 1 ])
test_x[ : , 1] = le.fit_transform(test_x[ : , 1 ])

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy='mean')
imputer.fit(train_x[ : , : ])
train_x[ : , :  ] = imputer.transform(train_x[ : , : ])
print(train_x)
imputer.fit(test_x[ : , : ])
test_x[ : , :  ] = imputer.transform(test_x[ : , : ])
print(test_x)




[[3.0 1.0 22.0 1.0 0.0 7.25]
 [1.0 0.0 38.0 1.0 0.0 71.2833]
 [3.0 0.0 26.0 0.0 0.0 7.925]
 ...
 [3.0 0.0 29.69911764705882 1.0 2.0 23.45]
 [1.0 1.0 26.0 0.0 0.0 30.0]
 [3.0 1.0 32.0 0.0 0.0 7.75]]
[[3.0 1.0 34.5 0.0 0.0 7.8292]
 [3.0 0.0 47.0 1.0 0.0 7.0]
 [2.0 1.0 62.0 0.0 0.0 9.6875]
 ...
 [3.0 1.0 38.5 0.0 0.0 7.25]
 [3.0 1.0 30.272590361445783 0.0 0.0 8.05]
 [3.0 1.0 30.272590361445783 1.0 1.0 22.3583]]


# Logistic Regression ( accuracy = 94.4) pretty good

In [ ]:

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(train_x , train_y) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Naive Bayes ( accuracy = 93.06 ) decent 

In [ ]:
"""
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(train_x , train_y)

"""

'\nfrom sklearn.naive_bayes import GaussianNB\nclassifier = GaussianNB()\nclassifier.fit(train_x , train_y)\n\n'

# Decison Tree ( accuracy = 78 % ) worst lol 

In [ ]:
"""from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy' , random_state = 0)
classifier.fit(train_x , train_y ) """


"from sklearn.tree import DecisionTreeClassifier\nclassifier = DecisionTreeClassifier(criterion = 'entropy' , random_state = 0)\nclassifier.fit(train_x , train_y ) "

# random forest classifier ( accuracy = 81 ) bad 

In [ ]:
""" from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy'  , random_state = 0)
classifier.fit(train_x , train_y) """

" from sklearn.ensemble import RandomForestClassifier\nclassifier = RandomForestClassifier(n_estimators = 10 , criterion = 'entropy'  , random_state = 0)\nclassifier.fit(train_x , train_y) "

In [ ]:

pred_y = classifier.predict(test_x)
print(np.concatenate((pred_y.reshape(len(pred_y),1), test_y.reshape(len(test_y),1)),1))


[[0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix
cm = confusion_matrix(test_y , pred_y )
print(cm)
accuracy = accuracy_score(test_y , pred_y)
print(accuracy)

[[253  13]
 [ 10 142]]
0.9449760765550239


In [ ]:
pd.to_